version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: pg-docker
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - dscatalog:/var/lib/mysql

volumes:
  dscatalog: